networks:
  ywang_vaster-network:
    name: ywang_vaster-network
    driver: bridge

services:
  db:
    hostname: db
    container_name: ywangvaster-db
    build:
      context: .
      dockerfile: ./containers/db/Dockerfile
    env_file: .env
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 4s
      timeout: 5s
      retries: 3

  firefly:
    image: ipac/firefly:latest
    container_name: ywangvaster-firefly
    volumes:
      - django_media:/firefly/shared-workarea
    environment:
      - VISUALIZE_FITS_SEARCH_PATH=/firefly/shared-workarea
    mem_limit: 4g

  web:
    hostname: web
    container_name: ywangvaster-web
    build:
      context: .
      dockerfile: ./containers/web/Dockerfile
    env_file: .env
    volumes:
      - ./ywangvaster_webapp:/ywangvaster_webapp
      - django_media:/ywangvaster_media
      - ./logs:/home/app/logs/
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:80/"
      start_period: 60s
      interval: 60s
      timeout: 20s
      retries: 20
    depends_on:
      db:
        condition: service_healthy
