services:
  db:
    environment:
      PROD: True

  web:
    environment:
      PROD: True
    volumes:
      - django_static:/ywangvaster_staticfiles
    expose:
      - 80

  nginx:
    hostname: nginx
    container_name: ywangvaster-nginx
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    volumes:
      - django_static:/ywangvaster_staticfiles
      - django_media:/ywangvaster_media
    ports:
      - 80:80
    depends_on:
      web:
        condition: service_healthy

  autoheal:
    image: willfarrell/autoheal
    container_name: ywangvaster-autoheal
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all

volumes:
  django_static:
