networks:
  ywang_vaster-network:
    name: ywang_vaster-network
    driver: bridge

volumes:
  django_media:
    # driver: local
    # driver_opts:
    #   type: "none"
    #   o: "bind"
    #   device: "<path-to-volume>/django_media"
  postgres_data:
    # driver: local
    # driver_opts:
    #   type: "none"
    #   o: "bind"
    #   device: "<path-to-volume>/postgres_data"

services:
  db:
    hostname: db
    container_name: ywangvaster-db
    build:
      context: .
      dockerfile: ./containers/db/Dockerfile
    env_file: .env
    environment:
      PROD: False
      DEBUG: 1
      DJANGO_LOG_LEVEL: INFO
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 4s
      timeout: 5s
      retries: 3

  web:
    hostname: web
    container_name: ywangvaster-web
    build:
      context: .
      dockerfile: ./containers/web/Dockerfile
    env_file: .env
    environment:
      PROD: False
      DEBUG: 1
      DJANGO_LOG_LEVEL: INFO
    volumes:
      - ./ywangvaster_webapp:/ywangvaster_webapp
      - django_media:/ywangvaster_media
      - ./logs:/home/app/logs/
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
