x-environment: &environment
  PROD: False

  # Postgres DB for Django UI

  # PostgreSQL settings
  DB_NAME: ywangvaster
  DB_USERNAME: ywangvaster
  DB_PASSWORD: vast1234star
  DB_HOST: db
  DB_PORT: 5432

  # Do not remove, otherwise postgres container won't initialise properly
  # Just has to be something that's non-zero
  POSTGRES_PASSWORD: password

  # DJango settings
  DEBUG: 1
  SECRET_KEY: foo
  DJANGO_LOG_LEVEL: INFO
  DJANGO_ALLOWED_HOSTS: localhost 0.0.0.0 [::1] *
  DJANGO_SUPERUSER_USERNAME: admin
  DJANGO_SUPERUSER_PASSWORD: test
  DJANGO_SUPERUSER_EMAIL: none@nothing.com
  DJANGO_SECRET_KEY: devkey
  PYTHONDONTWRITEBYTECODE: 1
  PYTHONUNBUFFERED: 1

networks:
  ywang_vaster-network:
    name: ywang_vaster-network
    driver: bridge

volumes:
  django_media:
    # driver: local
    # driver_opts:
    #   type: "none"
    #   o: "bind"
    #   device: "<path-to-volume>/django_media"
  postgres_data:
    # driver: local
    # driver_opts:
    #   type: "none"
    #   o: "bind"
    #   device: "<path-to-volume>/postgres_data"

services:
  db:
    hostname: db
    container_name: ywangvaster-db
    build:
      context: .
      dockerfile: ./containers/db/Dockerfile
    environment: *environment
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 4s
      timeout: 5s
      retries: 3

  web:
    hostname: web
    container_name: ywangvaster-web
    build:
      context: .
      dockerfile: ./containers/web/Dockerfile
    environment: *environment
    volumes:
      - ./ywangvaster_webapp:/ywangvaster_webapp
      - django_media:/ywangvaster_media
      - ./logs:/home/app/logs/
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
