# Generated by Django 4.2 on 2024-05-20 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0004_alter_atnfpulsar_dm_alter_atnfpulsar_p0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('beam_name', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Beam name')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='beam_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='candidate_app.beam', verbose_name='Beam ID used for finding the candidate'),
        ),
    ]
