# Generated by Django 5.1 on 2026-02-24 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0005_create_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating', to='candidate_app.tag'),
        ),
    ]
