# Generated by Django 6.0.2 on 2026-03-17 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0006_alter_rating_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['date']},
        ),
    ]
