# Generated by Django 6.0.2 on 2026-04-14 03:53

import candidate_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_app', '0008_candidate_is_best_beam'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='dynamic_spectra_png',
            field=models.FileField(blank=True, null=True, upload_to=candidate_app.models.cand_upload_path),
        ),
    ]
